import { DatePipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { errorMessage } from '../core/api';
import { PortalUser } from '../core/models';
import { IconComponent } from '../shared/icon.component';

@Component({ selector: 'sms-administrators', imports: [DatePipe, FormsModule, IconComponent], template: `
  <div class="page-heading"><div><span class="eyebrow">PLATFORM ADMINISTRATION</span><h1>Administrators<span class="heading-dot">.</span></h1><p>Manage who can access and configure the entire platform.</p></div><button class="button primary" (click)="openCreate()"><sms-icon name="plus"/>New administrator</button></div>
  @if (creating()) { <section class="panel padded create-panel"><div class="section-heading"><div><h2>Create administrator</h2><p>The password is stored as a secure hash and is never displayed again.</p></div><button class="icon-button" aria-label="Cancel administrator creation" (click)="creating.set(false)" [disabled]="saving()"><sms-icon name="close"/></button></div><form #createForm="ngForm" (ngSubmit)="create()"><div class="form-grid"><div><label for="admin-username">Username</label><input id="admin-username" name="username" [(ngModel)]="username" required minlength="3" maxlength="100" pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,99}" autocomplete="off"/></div><div><label for="admin-email">Email</label><input id="admin-email" name="email" [(ngModel)]="email" required maxlength="320" type="email" autocomplete="email"/></div><div><label for="admin-password">Temporary password</label><input id="admin-password" name="password" [(ngModel)]="password" required minlength="15" maxlength="128" type="password" autocomplete="new-password"/><p class="field-help">15–128 characters.</p></div></div><div class="form-actions"><button class="button" type="button" (click)="creating.set(false)" [disabled]="saving()">Cancel</button><button class="button primary" [disabled]="createForm.invalid || saving()">{{ saving() ? 'Creating…' : 'Create administrator' }}</button></div></form></section> }
  @if (resetting(); as administrator) { <section class="panel padded create-panel"><div class="section-heading"><div><h2>Reset password</h2><p>Set a new password for <strong>{{ administrator.username }}</strong>.</p></div><button class="icon-button" aria-label="Cancel password reset" (click)="cancelReset()" [disabled]="saving()"><sms-icon name="close"/></button></div><form #resetForm="ngForm" (ngSubmit)="resetPassword()"><label for="reset-password">New password</label><input id="reset-password" name="newPassword" [(ngModel)]="newPassword" required minlength="15" maxlength="128" type="password" autocomplete="new-password"/><p class="field-help">15–128 characters. Existing sessions remain valid until they expire or the account is deactivated.</p><div class="form-actions"><button class="button" type="button" (click)="cancelReset()" [disabled]="saving()">Cancel</button><button class="button primary" [disabled]="resetForm.invalid || saving()">{{ saving() ? 'Saving…' : 'Reset password' }}</button></div></form></section> }
  @if (success()) { <div class="notice success" role="status"><sms-icon name="check"/>{{ success() }}</div> }
  @if (error()) { <div class="notice error" role="alert"><sms-icon name="alert"/>{{ error() }}</div> }
  <section class="panel"><div class="panel-heading"><div><h2>Platform access</h2><p>At least one administrator must remain active.</p></div><button class="button compact" (click)="load()" [disabled]="loading()"><sms-icon name="refresh"/>Refresh</button></div>
    @if (loading()) { <div class="loading-state" role="status"><span class="spinner"></span>Loading administrators…</div> } @else if (administrators().length) { <div class="table-scroll"><table><thead><tr><th>Administrator</th><th>Access</th><th>Created at</th><th>Actions</th></tr></thead><tbody>@for (administrator of administrators(); track administrator.id) { <tr><td><div class="company-cell"><span class="company-avatar">{{ administrator.username.slice(0,2).toUpperCase() }}</span><div><strong>{{ administrator.username }}</strong><small class="cell-secondary mono">{{ administrator.id }}</small></div></div></td><td><span class="badge" [class.success]="administrator.isActive" [class.danger]="!administrator.isActive"><i class="status-dot"></i>{{ administrator.isActive ? 'Active' : 'Inactive' }}</span></td><td class="muted">{{ administrator.createdAt | date:'MM/dd/yyyy' }}</td><td><div class="button-row"><button class="button compact" (click)="startReset(administrator)" [disabled]="saving()"><sms-icon name="key"/>Reset password</button><button class="button compact" [class.destructive]="administrator.isActive" (click)="setActive(administrator)" [disabled]="saving()">{{ administrator.isActive ? 'Deactivate' : 'Activate' }}</button></div></td></tr> }</tbody></table></div> } @else { <div class="empty-state"><span class="empty-icon"><sms-icon name="shield"/></span><h3>No administrators found.</h3><p>Create an administrator to manage the platform.</p></div> }
  </section>` })
export class AdministratorsComponent {
  private readonly http = inject(HttpClient); private readonly destroyRef = inject(DestroyRef);
  readonly administrators = signal<PortalUser[]>([]); readonly loading = signal(false); readonly saving = signal(false);
  readonly creating = signal(false); readonly resetting = signal<PortalUser | null>(null); readonly error = signal(''); readonly success = signal('');
  username = ''; email = ''; password = ''; newPassword = '';
  constructor() { this.load(); }
  load() { this.loading.set(true); this.error.set(''); this.http.get<PortalUser[]>('/api/v1/admin/platform-users?role=administrator').pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.loading.set(false))).subscribe({ next: rows => this.administrators.set(rows), error: error => this.error.set(errorMessage(error)) }); }
  openCreate() { this.cancelReset(); this.success.set(''); this.error.set(''); this.creating.set(true); }
  create() { if (this.saving()) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.http.post('/api/v1/admin/platform-users', { username: this.username.trim(), email: this.email.trim(), password: this.password, role: 'administrator' }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.username = ''; this.email = ''; this.password = ''; this.creating.set(false); this.success.set('Administrator created.'); this.load(); }, error: error => this.error.set(errorMessage(error)) }); }
  startReset(administrator: PortalUser) { this.creating.set(false); this.error.set(''); this.success.set(''); this.newPassword = ''; this.resetting.set(administrator); }
  cancelReset() { this.resetting.set(null); this.newPassword = ''; }
  resetPassword() { const administrator = this.resetting(); if (!administrator || this.saving()) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.http.post(`/api/v1/admin/platform-users/${administrator.id}/reset-password`, { password: this.newPassword }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.cancelReset(); this.success.set(`Password reset for ${administrator.username}.`); }, error: error => this.error.set(errorMessage(error)) }); }
  setActive(administrator: PortalUser) { if (this.saving()) return; const action = administrator.isActive ? 'deactivate' : 'activate'; if (!confirm(`Do you want to ${action} ${administrator.username}?`)) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.http.put(`/api/v1/admin/platform-users/${administrator.id}/state`, { isActive: !administrator.isActive }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.success.set(`${administrator.username} ${administrator.isActive ? 'deactivated' : 'activated'}.`); this.load(); }, error: error => this.error.set(errorMessage(error)) }); }
}
