import { DatePipe } from '@angular/common';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { errorMessage } from '../core/api';
import { BlockedNumber } from '../core/models';
import { IconComponent } from '../shared/icon.component';

@Component({ selector: 'sms-opt-outs', imports: [DatePipe, FormsModule, IconComponent], template: `
  <div class="page-heading"><div><span class="eyebrow">SMS COMPLIANCE</span><h1>Opt-outs<span class="heading-dot">.</span></h1><p>Numbers on this list cannot receive outbound messages from your company.</p></div><div class="button-row"><button class="button" (click)="download()"><sms-icon name="send"/>Export CSV</button><label class="button"><sms-icon name="plus"/>Import CSV<input hidden type="file" accept=".csv,text/csv" (change)="importFile($event)"/></label><button class="button primary" (click)="creating.set(true)"><sms-icon name="plus"/>Block number</button></div></div>
  @if (creating()) { <section class="panel padded create-panel"><div class="section-heading"><div><h2>Block a number</h2><p>Use international format, for example +15551234567.</p></div><button class="icon-button" (click)="creating.set(false)"><sms-icon name="close"/></button></div><form #form="ngForm" (ngSubmit)="add()"><div class="form-grid"><div><label for="blocked-phone">Phone number</label><input id="blocked-phone" name="phone" [(ngModel)]="phoneNumber" required maxlength="32"/></div><div><label for="blocked-reason">Reason</label><input id="blocked-reason" name="reason" [(ngModel)]="reason" maxlength="200"/></div></div><div class="form-actions"><button class="button" type="button" (click)="creating.set(false)">Cancel</button><button class="button primary" [disabled]="form.invalid || saving()">{{ saving() ? 'Saving…' : 'Block number' }}</button></div></form></section> }
  @if (success()) { <div class="notice success" role="status"><sms-icon name="check"/>{{ success() }}</div> } @if (error()) { <div class="notice error" role="alert"><sms-icon name="alert"/>{{ error() }}</div> }
  <section class="panel"><div class="panel-heading"><div><h2>Blocked numbers</h2><p>STOP, UNSUBSCRIBE and CANCEL are added automatically. START removes the block.</p></div><button class="button compact" (click)="load()" [disabled]="loading()"><sms-icon name="refresh"/>Refresh</button></div>
    @if (loading()) { <div class="loading-state"><span class="spinner"></span>Loading opt-outs…</div> } @else if (rows().length) { <div class="table-scroll"><table><thead><tr><th>Phone number</th><th>Source</th><th>Reason</th><th>Blocked at</th><th>Action</th></tr></thead><tbody>@for (row of rows(); track row.id) { <tr><td class="mono">{{ row.phoneNumber }}</td><td>{{ row.source }}</td><td>{{ row.reason || '—' }}</td><td>{{ row.createdAt | date:'medium' }}</td><td><button class="button compact destructive" (click)="remove(row)" [disabled]="saving()">Unblock</button></td></tr> }</tbody></table></div> } @else { <div class="empty-state"><span class="empty-icon"><sms-icon name="shield"/></span><h3>No blocked numbers.</h3><p>Inbound opt-out keywords and manually blocked numbers will appear here.</p></div> }
  </section>` })
export class OptOutsComponent {
  private readonly http = inject(HttpClient); private readonly destroyRef = inject(DestroyRef);
  readonly rows = signal<BlockedNumber[]>([]); readonly loading = signal(false); readonly saving = signal(false); readonly creating = signal(false); readonly error = signal(''); readonly success = signal('');
  phoneNumber = ''; reason = '';
  constructor() { this.load(); }
  load() { this.loading.set(true); this.http.get<BlockedNumber[]>('/api/v1/opt-outs').pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.loading.set(false))).subscribe({ next: rows => this.rows.set(rows), error: e => this.error.set(errorMessage(e)) }); }
  add() { this.saving.set(true); this.error.set(''); this.http.post('/api/v1/opt-outs', { phoneNumber: this.phoneNumber, reason: this.reason || null }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.creating.set(false); this.phoneNumber = ''; this.reason = ''; this.success.set('Number blocked.'); this.load(); }, error: e => this.error.set(errorMessage(e)) }); }
  remove(row: BlockedNumber) { if (!confirm(`Unblock ${row.phoneNumber}?`)) return; this.saving.set(true); this.http.delete(`/api/v1/opt-outs/${row.id}`).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.success.set('Number unblocked.'); this.load(); }, error: e => this.error.set(errorMessage(e)) }); }
  download() { this.http.get('/api/v1/opt-outs/export', { observe: 'response', responseType: 'blob' }).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: (response: HttpResponse<Blob>) => { const url = URL.createObjectURL(response.body!); const link = document.createElement('a'); link.href = url; link.download = 'sms-opt-outs.csv'; link.click(); URL.revokeObjectURL(url); }, error: e => this.error.set(errorMessage(e)) }); }
  importFile(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; file.text().then(text => { const rows = text.split(/\r?\n/).slice(1).filter(Boolean).map(line => { const values = line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g)?.map(value => value.replace(/,$/, '').trim().replace(/^"|"$/g, '').replace(/""/g, '"')) ?? []; return { phoneNumber: values[0], reason: values.length >= 3 ? values[2] || null : values[1] || null }; }); this.http.post('/api/v1/opt-outs/import', rows).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: () => { this.success.set(`${rows.length} numbers imported.`); this.load(); }, error: e => this.error.set(errorMessage(e)) }); }).finally(() => input.value = ''); }
}
