import { DatePipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { errorMessage } from '../core/api';
import { PortalPermissionRole, PortalUser } from '../core/models';
import { IconComponent } from '../shared/icon.component';

@Component({ selector: 'sms-tenant-users', imports: [DatePipe, FormsModule, IconComponent], template: `
  <div class="page-heading"><div><span class="eyebrow">WORKSPACE ADMINISTRATION</span><h1>Users<span class="heading-dot">.</span></h1><p>Manage the people who can access your company workspace.</p></div><button class="button primary" (click)="openCreate()"><sms-icon name="plus"/>New user</button></div>
  @if (creating()) { <section class="panel padded create-panel"><div class="section-heading"><div><h2>Create user</h2><p>The password is stored securely and is never displayed again.</p></div><button class="icon-button" aria-label="Cancel user creation" (click)="cancelCreate()" [disabled]="saving()"><sms-icon name="close"/></button></div><form #form="ngForm" (ngSubmit)="create()"><div class="form-grid"><div><label for="user-username">Username</label><input id="user-username" name="username" [(ngModel)]="username" required minlength="3" maxlength="100" pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,99}" autocomplete="off"/></div><div><label for="user-role">Role</label><select id="user-role" name="role" [(ngModel)]="role"><option value="user">User</option><option value="administrator">Administrator</option></select><p class="field-help">Administrators can manage users and workspace settings.</p></div><div><label for="user-password">Temporary password</label><input id="user-password" name="password" [(ngModel)]="password" required minlength="15" maxlength="128" type="password" autocomplete="new-password"/><p class="field-help">15–128 characters.</p></div></div><div class="form-actions"><button class="button" type="button" (click)="cancelCreate()" [disabled]="saving()">Cancel</button><button class="button primary" [disabled]="form.invalid || saving()">{{ saving() ? 'Creating…' : 'Create user' }}</button></div></form></section> }
  @if (resetting(); as user) { <section class="panel padded create-panel"><div class="section-heading"><div><h2>Reset password</h2><p>Set a new password for <strong>{{ user.username }}</strong>.</p></div><button class="icon-button" aria-label="Cancel password reset" (click)="cancelReset()" [disabled]="saving()"><sms-icon name="close"/></button></div><form #resetForm="ngForm" (ngSubmit)="resetPassword()"><label for="new-password">New password</label><input id="new-password" name="newPassword" [(ngModel)]="newPassword" required minlength="15" maxlength="128" type="password" autocomplete="new-password"/><p class="field-help">15–128 characters.</p><div class="form-actions"><button class="button" type="button" (click)="cancelReset()" [disabled]="saving()">Cancel</button><button class="button primary" [disabled]="resetForm.invalid || saving()">{{ saving() ? 'Saving…' : 'Reset password' }}</button></div></form></section> }
  @if (success()) { <div class="notice success" role="status"><sms-icon name="check"/>{{ success() }}</div> } @if (error()) { <div class="notice error" role="alert"><sms-icon name="alert"/>{{ error() }}</div> }
  <section class="panel"><div class="panel-heading"><div><h2>Workspace access</h2><p>Users can access only this tenant's data.</p></div><button class="button compact" (click)="load()" [disabled]="loading()"><sms-icon name="refresh"/>Refresh</button></div>
    @if (loading()) { <div class="loading-state" role="status"><span class="spinner"></span>Loading users…</div> } @else if (users().length) { <div class="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Access</th><th>Created at</th><th>Actions</th></tr></thead><tbody>@for (user of users(); track user.id) { <tr><td><div class="company-cell"><span class="company-avatar">{{ user.username.slice(0,2).toUpperCase() }}</span><div><strong>{{ user.username }}</strong><small class="cell-secondary mono">{{ user.id }}</small></div></div></td><td>{{ user.role === 'administrator' ? 'Administrator' : 'User' }}</td><td><span class="badge" [class.success]="user.isActive" [class.danger]="!user.isActive"><i class="status-dot"></i>{{ user.isActive ? 'Active' : 'Inactive' }}</span></td><td class="muted">{{ user.createdAt | date:'MM/dd/yyyy' }}</td><td><div class="button-row"><button class="button compact" (click)="startReset(user)" [disabled]="saving()"><sms-icon name="key"/>Reset password</button><button class="button compact" [class.destructive]="user.isActive" (click)="setActive(user)" [disabled]="saving()">{{ user.isActive ? 'Deactivate' : 'Activate' }}</button></div></td></tr> }</tbody></table></div> } @else { <div class="empty-state"><span class="empty-icon"><sms-icon name="users"/></span><h3>No users found.</h3><p>Create a user to grant workspace access.</p></div> }
  </section>` })
export class TenantUsersComponent {
  private readonly http = inject(HttpClient); private readonly destroyRef = inject(DestroyRef);
  readonly users = signal<PortalUser[]>([]); readonly loading = signal(false); readonly saving = signal(false); readonly creating = signal(false); readonly resetting = signal<PortalUser | null>(null); readonly error = signal(''); readonly success = signal('');
  username = ''; password = ''; newPassword = ''; role: PortalPermissionRole = 'user';
  constructor() { this.load(); }
  load() { this.loading.set(true); this.error.set(''); this.http.get<PortalUser[]>('/api/v1/tenant/users').pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.loading.set(false))).subscribe({ next: rows => this.users.set(rows), error: error => this.error.set(errorMessage(error)) }); }
  openCreate() { this.cancelReset(); this.username = ''; this.password = ''; this.role = 'user'; this.error.set(''); this.success.set(''); this.creating.set(true); }
  cancelCreate() { this.creating.set(false); this.username = ''; this.password = ''; }
  create() { if (this.saving()) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.http.post('/api/v1/tenant/users', { username: this.username.trim(), password: this.password, role: this.role }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.cancelCreate(); this.success.set('User created.'); this.load(); }, error: error => this.error.set(errorMessage(error)) }); }
  startReset(user: PortalUser) { this.creating.set(false); this.newPassword = ''; this.error.set(''); this.success.set(''); this.resetting.set(user); }
  cancelReset() { this.resetting.set(null); this.newPassword = ''; }
  resetPassword() { const user = this.resetting(); if (!user || this.saving()) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.http.post(`/api/v1/tenant/users/${user.id}/reset-password`, { password: this.newPassword }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.cancelReset(); this.success.set(`Password reset for ${user.username}.`); }, error: error => this.error.set(errorMessage(error)) }); }
  setActive(user: PortalUser) { if (this.saving()) return; const action = user.isActive ? 'deactivate' : 'activate'; if (!confirm(`Do you want to ${action} ${user.username}?`)) return; this.saving.set(true); this.error.set(''); this.success.set(''); this.http.put(`/api/v1/tenant/users/${user.id}/state`, { isActive: !user.isActive }).pipe(takeUntilDestroyed(this.destroyRef), finalize(() => this.saving.set(false))).subscribe({ next: () => { this.success.set(`${user.username} ${user.isActive ? 'deactivated' : 'activated'}.`); this.load(); }, error: error => this.error.set(errorMessage(error)) }); }
}
